baseURL = "https://lokal.ninja/sachsen-anhalt"
languageCode = "de-DE"
title = "Lokal Ninja - Sachsen-Anhalt"
theme = "ln-base"

disableKinds = ["taxonomy", "taxonomyTerm"]

[outputs]
  home = ["HTML"]

[params]
  org = "lokal-ninja"
  region = "Sachsen-Anhalt"
  repo = "sachsen-anhalt"
